services:
  bitcoin-core-regtest:
    image: ruimarinho/bitcoin-core:23.0
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ${HOME}/.bitcoin:/home/bitcoin/.bitcoin
    command: [
      -addresstype=legacy,
      -txindex,
      -printtoconsole,
      # Regression test creates an empty private blockchain to test with.
      -regtest=1,
      -rpcallowip=0.0.0.0/0,
      # What IP addresses this node will listen for requests at. 0.0.0.0 -> any address in the docker container.
      # An example of an IP address of the docker container is 172.18.0.2
      -rpcbind=0.0.0.0,
      # {user}:{salt}${hash}
      -rpcauth=jayerds:24f27f823ea2576025b6aadd803e087f$$b7967009989651168bbc002f4511b3faba53362f0d62ff2daf62b63752c7a5ac    
      
      ]

      15dBtds5LQeZ6C8sKdKkfnAgQflpfr5gEWR-UwFpmds=